/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        "on-secondary-container": "#b0b1ff",
        "on-tertiary-fixed": "#291800",
        "on-primary-fixed": "#002116",
        "primary-fixed-dim": "#2fe0aa",
        "secondary-container": "#312ec5",
        "secondary-fixed": "#e1e0ff",
        "surface-container-high": "#292a2c",
        "on-secondary-fixed-variant": "#2e2bc2",
        "surface-bright": "#38393b",
        "tertiary-container": "#f6a724",
        "secondary-fixed-dim": "#c1c1ff",
        secondary: "#c1c1ff",
        "on-primary": "#003828",
        "on-error-container": "#ffdad6",
        "on-surface": "#e3e2e5",
        "on-tertiary": "#452b00",
        "error-container": "#93000a",
        "on-error": "#690005",
        "inverse-surface": "#e3e2e5",
        "surface-container-low": "#1b1c1e",
        tertiary: "#ffc983",
        "surface-container-highest": "#343537",
        "on-secondary-fixed": "#07006c",
        surface: "#121315",
        "on-tertiary-fixed-variant": "#633f00",
        "on-primary-fixed-variant": "#00513b",
        error: "#ffb4ab",
        "surface-container-lowest": "#0d0e10",
        primary: "#44edb7",
        "on-secondary": "#1200a9",
        "tertiary-fixed-dim": "#ffb955",
        background: "#121315",
        "on-primary-container": "#00533c",
        "primary-container": "#00d09c",
        "outline-variant": "#3c4a43",
        "primary-fixed": "#59fdc5",
        "surface-container": "#1f2022",
        "zk-purple": "#5D5FEF",
        outline: "#85948c",
        "inverse-on-surface": "#303033",
        "on-tertiary-container": "#654000",
        "on-background": "#e3e2e5",
        "surface-tint": "#2fe0aa",
        "on-surface-variant": "#bacac1",
        "inverse-primary": "#006c4f",
        "surface-dim": "#121315",
        "surface-variant": "#343537",
        "tertiary-fixed": "#ffddb4",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        mono: ["JetBrains Mono"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        "spin-slow": "spin 10s linear infinite",
        "spin-reverse-slow": "spin 5s linear infinite reverse",
      },
    },
  },
  plugins: [],
};